export {default as Navbar} from './navbar'
export {default as Home} from './home'
export {default as LevelOne} from './levelOne'
export {default as LevelTwo} from './levelTwo'
export {default as LevelThree} from './levelThree'
export {default as GameOver} from './GameOver'
export {default as Victory} from './victory'
